name = "MyExample1"
uuid = "8e390c2b-d4f6-4202-9e23-0a75ec0090a3"
authors = ["Chelsea Trotter"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
